HL_API_URL = "https://api.hyperliquid.xyz/info"

PAIRS = ["DOGE", "SUI", "BTC", "LINK", "ETH", "NEAR", "XRP", "SOL", "WIF", "AVAX", "HYPE", "INJ"]

SCAN_INTERVAL_SECONDS  = 30
PRICE_INTERVAL_SECONDS = 8
PAPER_MODE             = True

J15M_SHORT_GATE  = 80
J15M_LONG_GATE   = 20
J1H_SHORT_MIN    = 60
J1H_LONG_MAX     = 40

RSI15M_SHORT_MIN = 65
RSI15M_LONG_MAX  = 35

DEPTH_GATE_PCT   = 55

ATR_SL_MULTIPLIER = 1.0

TP1_R = 1.0
TP2_R = 1.5

LEVERAGE_HIGH = 10
LEVERAGE_MID  = 7
LEVERAGE_LOW  = 5

COOLDOWN_SECONDS      = 1800
CONSECUTIVE_LOSS_STOP = 3
DAILY_LOSS_LIMIT      = -500.0

MARGIN_PER_TRADE = 2000.0
MARGIN_HARD_CAP  = 25000.0

ADX_FADE_MAX = 60

SESSION_FILTER_ENABLED = False
PLACE_EXCHANGE_SL      = True

PAIR_ADX_OVERRIDES: dict = {}
